name: 'Test'
on:
  push:
    branches:
      - iz1

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gcovr
      run: sudo apt-get install python3-setuptools && sudo pip3 install git+https://github.com/gcovr/gcovr.git
    - name: Install Valgrind
      run: sudo apt-get install -y valgrind
    - name: Install GoogleTests
      run: sudo apt-get install -y googletest && sudo apt-get install libgtest-dev
    - name: Install CppCheck
      run: sudo apt-get install -y cppcheck
    - name: Run Linter For .C
      run: cd project/src && cppcheck *.c
    - name: Run Linter For .H
      run: cd project/include && cppcheck *.h
    - name: Make Build Dir & CMake
      run: mkdir project/build && cd project/build && cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: Make
      run: cd project/build && make
    - name: Valgrind & Tests
      run: cd project/build && valgrind --tool=memcheck --leak-check=yes ./tests
    - name: Code Coverage
      run: cd project/build && make coverage
    - name: Code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: project/build/coverage/index.html
